services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tcal-analyzer-web
    tty: true
    ports:
      - "5173:5173"
    environment:
      - ZSH_DISABLE_COMPFIX=true
      - DISABLE_AUTO_UPDATE=true
      - PS1
      - TERM=xterm-256color
      - COLORTERM=truecolor
    volumes:
      - type: bind
        source: ~/.ssh
        target: /root/.ssh
        read_only: true

      - type: bind
        source: ~/.claude
        target: /root/.claude

      - type: bind
        source: .
        target: /mnt/workspace

      - type: bind
        source: ~/.zshrc
        target: /root/.zshrc
        read_only: true

      - type: bind
        source: ~/.oh-my-zsh
        target: /root/.oh-my-zsh

      - type: bind
        source: ~/.p10k.zsh
        target: /root/.p10k.zsh
        read_only: true

      - type: bind
        source: ~/.config/nvim
        target: /root/.config/nvim
        read_only: true

      - type: bind
        source: ~/.local/share/nvim
        target: /root/.local/share/nvim
